---
structname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  # configuration on package level
  net/http:
    config:
      dir: mocks/net/http
    interfaces:
      ResponseWriter:

  aksa.local/scrum/server/timeprovider:
    interfaces:
      TimeProvider:

  aksa.local/scrum/server/boards:
    interfaces:
      BoardService:
      BoardDatabase:

  aksa.local/scrum/server/realtime:
    interfaces:
      Client:

  aksa.local/scrum/server/reactions:
    interfaces:
      ReactionService:
      ReactionDatabase:

  aksa.local/scrum/server/hash:
    interfaces:
      Hash:

  aksa.local/scrum/server/health:
    interfaces:
      HealthService:
      HealthDatabase:

  aksa.local/scrum/server/sessions:
    interfaces:
      SessionService:
      SessionDatabase:
      SessionApi:

  aksa.local/scrum/server/sessionrequests:
    interfaces:
      SessionRequestService:
      SessionRequestDatabase:
      Websocket:

  aksa.local/scrum/server/users:
    interfaces:
      UserService:
      UserDatabase:
      UsersApi:

  aksa.local/scrum/server/notes:
    interfaces:
      NotesService:
      NotesDatabase:

  aksa.local/scrum/server/votings:
    interfaces:
      VotingService:
      VotingDatabase:

  aksa.local/scrum/server/columntemplates:
    interfaces:
      ColumnTemplateService:
      ColumnTemplateDatabase:

  aksa.local/scrum/server/boardtemplates:
    interfaces:
      BoardTemplateService:
      BoardTemplateDatabase:

  aksa.local/scrum/server/columns:
    interfaces:
      ColumnService:
      ColumnDatabase:

