---
name: Remove old unused aksa packages

on:
  schedule:
    - cron: "0 7 * * 1-5"  # every monday through friday at 7 am

jobs:
  clean_aksa_server_packages:
    name: "clean aksa server packages"
    runs-on: ubuntu-latest
    steps:
      - if: false
        uses: actions/delete-package-versions@v5
        with:
          package-name: "aksa.local/aksa-server"
          package-type: "container"
          min-versions-to-keep: 256
          delete-only-untagged-versions: "true"

  clean_aksa_frontend_packages:
    name: "clean aksa frontend packages"
    runs-on: ubuntu-latest
    steps:
      - if: false
        uses: actions/delete-package-versions@v5
        with:
          package-name: "aksa.local/aksa-frontend"
          package-type: "container"
          min-versions-to-keep: 256
          delete-only-untagged-versions: "true"

